name: panda_wordchanger
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter: { sdk: flutter }
  flutter_flavorizr: ^2.1.3
  flutter_screenutil: ^5.4.0
  import_sorter: ^4.6.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  pedantic_mono: ^1.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ic_launcher.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "panda-wordchanger-dev"
      android:
        applicationId: "com.ukihome.panda_wordchanger.dev"
        firebase:
          config: ".firebase/dev/google-services.json"
      ios:
        bundleId: "com.ukihome.panda-wordchanger.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"
    prd:
      app:
        name: "panda-wordchanger-prd"
      android:
        applicationId: "com.ukihome.panda_wordchanger.prd"
        firebase:
          config: ".firebase/prd/google-services.json"
      ios:
        bundleId: "com.ukihome.panda-wordchanger.prd"
        firebase:
          config: ".firebase/prd/GoogleService-Info.plist"